spring.application.name=SpringSecurityDemo


spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_security_app
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name =org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
